CREATE TABLE [Staging].[StgSalesOrderHeader] (
    [SalesOrderID]           INT           NOT NULL,
    [RevisionNumber]         TINYINT       NOT NULL,
    [OrderDate]              DATETIME      NOT NULL,
    [DueDate]                DATETIME      NOT NULL,
    [ShipDate]               DATETIME      NULL,
    [Status]                 TINYINT       NOT NULL,
    [OnlineOrderFlag]        BIT           NOT NULL,
    [SalesOrderNumber]       VARCHAR (25)  NOT NULL,
    [PurchaseOrderNumber]    VARCHAR (25)  NULL,
    [AccountNumber]          VARCHAR (25)  NULL,
    [CustomerID]             INT           NOT NULL,
    [ShipMethod]             VARCHAR (50)  NOT NULL,
    [CreditCardApprovalCode] VARCHAR (15)  NULL,
    [SubTotal]               MONEY         NOT NULL,
    [TaxAmt]                 MONEY         NOT NULL,
    [Freight]                MONEY         NOT NULL,
    [TotalDue]               MONEY         NOT NULL,
    [Comment]                VARCHAR (128) NULL,
    [ModifiedDate]           DATETIME      NOT NULL,
    [ShipToAddressID]        INT           NOT NULL,
    [BillToAddressID]        INT           NOT NULL,
    [LoadExecutionId]        BIGINT        NOT NULL
);