CREATE VIEW [Cube].[FactOrders]
AS 
SELECT [IDOrderDate]
      ,[IDShipDate]
      ,[IDDueDate]
      ,[IDProduct]
      ,[IDCustomer]
      ,[IDBillingAddress]
      ,[IDShippingAddress]
      ,[IDOrderProvenance]
      ,[OrderQy]
      ,[UnitPrice]
      ,[Discount]
      ,[TaxAmount]
      ,[Freight]
  FROM [DW].[FactOrders]